version: "3.9"
services:
  PostgreSQLDB:
    networks:
      - host
    image: postgres:15.2-alpine
    restart: always
    # deploy:
    #   mode: replicated
    #   replicas: 1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dbPostgreSQL:/var/lib/postgresql/data

  mongoDB:
    networks:
      - host
    image: mongo:6.0
    restart: always
    ports:
      - ${MONGO_DB_PORT}:27017
    # deploy:
    #   mode: replicated
    #   replicas: 1
    volumes:
      - mongo_storage:/data/db
