version: "3.9"
services:
  PostgreSQLDB:
    
    image: postgres:15.2-alpine
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - dbPostgreSQL:/var/lib/postgresql/data

  mongoDB:
    
    image: mongo:6.0
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - mongo_storage:/data/db
